### PR TITLE
Move actual force shutdown to own coro

### PR DESCRIPTION
**Pull request by kai3341**
Reason -- unittest breaks logger shutdown

### CODE REVIEW

**Comment by daltonmatos** [comment]
Hello @kai3341,

Thank you for your interest in aiologger and to dedicate your time to open this PR.

I woul like to know if you can help me reproduce the error you faced and that motivated this PR. Could you post here the step-by-step on how to reproduce the problem using the `master` branch?

Thanks,

**Comment by kai3341** [comment]
> Could you post here the step-by-step on how to reproduce the problem using the `master` branch?

https://gist.github.com/kai3341/4028e1fcb29bc06a88ec25f232a48c1d

**Comment by daltonmatos** [comment]
Thanks @kai3341. I will take a look and try to understand the problem.

**Comment by kai3341** [comment]
I have already done some research:
https://github.com/kai3341/aiologger/commits/fix-file-handler

**Comment by daltonmatos** [comment]
Hello @kai3341,

Me and @diogommartins checked that your example tests fails with and without the modification on this PR. But we also identified a problem related to the change of the I/O loop and for that we thank you for discovering and reporting the bug.

We checked the code in more detail and confirmed that a fix can be done, on these lines:

```patch
--- aiologger/handlers/files.py	(revision decf78c972403b5aaf90b0c9fb5b1e299d2f3a6b)
+++ aiologger/handlers/files.py	(date 1559827146400)
@@ -35,8 +35,7 @@
         self.mode = mode
         self.encoding = encoding
         self.stream: AsyncTextIOWrapper = None
-        self._initialization_lock = asyncio.Lock()
-        self._initialization_lock = asyncio.Lock(loop=self.loop)
+        self._initialization_lock: Optional[asyncio.Lock] = None
 
     @property
     def initialized(self):
@@ -47,6 +46,8 @@
         Open the current base file with the (original) mode and encoding.
         Return the resulting stream.
         """
+        if self._initialization_lock is None:
+            self._initialization_lock = asyncio.Lock(loop=self.loop)
         async with self._initialization_lock:
             if not self.initialized:
                 self.stream = await aiofiles.open(

```

Would you like to implement this fix? What's missing here is a TestClass that changes the loop between two testcases, but uses the same instance of a Logger and its Handler.

## Why your tests catched the bug

Your code snipet uses aiohttp's `unittest_run_loop` and you TestClass inherits from `AioHTTPTestCase`. What this combination does is that for every testcase inside your class, a new I/O loop is closed and re created. That's why the tests fails, because `aiologger` is not prepared for this loop change.

**Comment by kai3341** [comment]
> Would you like to implement this fix? What's missing here is a TestClass that changes the loop between two testcases, but uses the same instance of a Logger and its Handler.

Oooh, got it! I'll do it

**Comment by kai3341** [comment]
@daltonmatos, *YES*. I applied your changes and it solved ResourceWarning

**Comment by daltonmatos** [comment]
> @daltonmatos, _YES_. I applied your changes and it solved ResourceWarning

That's awesome @kai3341. Would you mind opening a new fresh branch with only the right fix (and its tests) applied?

Also, it seems that you commited in yout fork's `master` branch. You should always commit on topic branches. Commiting on your `master` branch makes it difficult to open PRs. Even we, developing aiologger, don't commit to the `master` branch (this branch is write protected by github). The `master` branch only receives code through merges.

Another observation: You seem to be comitting with two different `Author` info:
- Anton Kovalevich <kai3341@gmail.com>
- Vadim Beletsky <vadim.beletsky@solbeg.com>

The second info, using the `@solbeg.com` email is not correclty linking to your github profile. What this means is that this contributions will not be linked to your profile. Here you have 2 options:

- Add this email to your github account;
- Reconfigure your git client to commit with `@gmail.com` email.

Thanks,

**Comment by kai3341** [comment]
@daltonmatos, i'll have a time to do it. But each change i've done inside separated branch. You see branch name exactly equaling to my local branch

 What about two different authors... It's some kind of circus, i temporary have to use my team lead's credentials. I don't know the easiest way. I need for a day to get the answer

**Comment by kai3341** [comment]
I have to re-open this merge request

**Comment by daltonmatos** [comment]
Hello @kai3341,

There's no problem in having multiple author infos, the problem I see is having a commit that does not link to any github profile. That's why I suggested the change. But you can do what you think is best, no worries. :tada: :tada:

**Comment by kai3341** [comment]
@daltonmatos actually this commit has the only author. It was some chaos with credentials and i fixed it now. Thanks!

**Pull request closed without merging**
