### PR TITLE
#16 - AsyncFileHandler

### PR DESCRIPTION
**Pull request by diogommartins**
- Adding aiofiles==0.4.0 as a dependency
- Adding an AsyncFileHandler implementation

### CODE REVIEW

**Comment by daltonmatos** [comment]
Implements #16

**Comment by daltonmatos** [comment]
Maybe it would be a good idea to add aiofiles as an optional dependency[1], using the `extra_requires` from setuptools. What do you think, @diogommartins ?

[1] https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by diogommartins** [comment]
> Maybe it would be a good idea to add aiofiles as an optional dependency[1], using the `extra_requires` from setuptools. What do you think, @diogommartins ?
> 
> [1] https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

I thinks it's a good idea, @daltonmatos . Since this dependency is only used at `aiologger.handlers.files` , it's already decoupled. Nevertheless, having a test to validate that for future refactors would be nice. Any ideia of how could we do that ?

**Comment by daltonmatos** [comment]
The tests already exist. I think that `aiofiles` should be moved to `dev-packages` inside Pipfile. This way whoever hacks into aiologger's code will have `aiofiles` always installed and the tests would run normally.

Bu insite `setup.py`, `aiofiles` would be listed in `optional_requires`. This way, everyone that want to use aiologger with `aiofiles` would install it like this: `pip install aiologger[aiofiles]`.

What do you think?

**Comment by diogommartins** [comment]
Moved aiofiles itnto `extras_require` @daltonmatos

**Comment by diogommartins** [comment]
> Ótimo! Acho que vale esperar retorno dos testes da pessoa que está validando e adicionar documentação para essa feature. Ensinando configurar um file logger e como instalar o `aiologger` com suporte a file logger.
> 
> O que acha?

Essa branch só tem 

> Ótimo! Acho que vale esperar retorno dos testes da pessoa que está validando e adicionar documentação para essa feature. Ensinando configurar um file logger e como instalar o `aiologger` com suporte a file logger.
> 
> O que acha?

The code he is currently testing is implemented on `feature/16-rotating-file-handler` branch. This PR (#39) contains only the basic building blocks for the `AsyncTimedRotatingFileHandler`. I think we can merge this PR and work on all the documentation related to files at `feature/16-rotating-file-handler`, before actually releasing a new version, or we can write a documentation only for `AsyncFileHandler` and `pip install aiologger[aiofiles]` (or should it be `pip install aiologger[files]` ?)

**Comment by diogommartins** [comment]
I've added some documentation. Can you review it, @daltonmatos  ?

**Comment by diogommartins** [comment]
> Feito. Acho que podemos pedir uma segunda validação para o quem está nos ajudando.
> 
> Acha que vale completar os exempos com a criaçao do Logger + adição do handler e chamada a logger.info()? Ou acha que complicaria demais?
> 
> 🎉

Acho válido, mas a documentação já tá ficando bem extensa pra um README.md. Acho que o próximo passo vai ser partir pra sphinx+readthedocs ou outra coisa

**Comment by daltonmatos** [comment]
> Acho válido, mas a documentação já tá ficando bem extensa pra um README.md. Acho que o próximo passo vai ser partir pra sphinx+readthedocs ou outra coisa

Justo. :tada:

**Pull request merged**
