### PR TITLE
Move actual force shutdown to own coro

### PR DESCRIPTION
**Pull request by kai3341**
Add ability to do forced logger shutdown

### CODE REVIEW

**Comment by daltonmatos** [comment]
I thin this PR should apply the change proposed here: https://github.com/B2W-BIT/aiologger/pull/67#issuecomment-499501302

and confirmed here: https://github.com/B2W-BIT/aiologger/pull/67#issuecomment-499526885

Also, don't forget to fix your fork's master branch. It should be identical do the original master branch. What do you think about doing this **brefore** re-opening the PRs? I think that this should make things easier.

**Comment by kai3341** [comment]
I closed #67 to fix chaos with credentials

**Comment by kai3341** [comment]
@daltonmatos, I already merged `master` branch into this, so this branch is actual

**Comment by daltonmatos** [comment]
Hello @kai3341,

What's this PR really fixing? Isn't the fix mentionned here (https://github.com/B2W-BIT/aiologger/pull/71#issuecomment-500860873) already applyed to #70?

What about closing this PR?

Thanks,

**Comment by kai3341** [comment]
Hi @daltonmatos ,

No, this PRs are different and independent: they changes different files

I need in way to guarantee close logger on application shutdown

Unittest breaks aiologger shutdown by multiple reinitialization reason: it doesn't know that handlers are reinited. And actually there is no difference on application shutdown

**Comment by daltonmatos** [comment]
Hello @kai3341, 

all set to this PR to be merged. You just need to update it with the newest commits from the `master` branch of the original project.

As soon as you update and the CI runs, if it's all green we can merge the code.

Thanks,

**Comment by kai3341** [comment]
> As soon as you update and the CI runs, if it's all green we can merge the code.

Hi, @daltonmatos. Done;

**Pull request merged**
