### PR TITLE
Fixed trailing newline position

### PR DESCRIPTION
**Pull request by kai3341**

### CODE REVIEW

**Comment by daltonmatos** [comment]
Ref. #78

**Comment by daltonmatos** [comment]
Hello @kai3341, thanks for the PR. Could you demonstrate the write order problem with a testcase? 

If not, can you provide a code snippet that show the problem happening?

In what sitiations did you see mixed log lines?

thanks,

**Comment by kai3341** [comment]
> Nice catch, @kai3341! Your fix makes total sense.
> I believe that writing a test to validate that `stream.write` is always called with a string ending with `\n` is enough to validate that we won't make the same mistake again.

It works a little differently. Single write is always atomic. But there were two write calls

@daltonmatos @diogommartins maybe it's good idea to move handling newline to formatter. For example, formatter can generate JSON, so newline symbols will not be required

**Comment by kai3341** [comment]
@daltonmatos @diogommartins I need your feedback. Maybe it's good idea to remove adding trailing `\n` at handler level and move it to formatter level?

**Comment by daltonmatos** [comment]
> @daltonmatos @diogommartins I need your feedback. Maybe it's good idea to remove adding trailing `\n` at handler level and move it to formatter level?

Hello @kai3341, 

I think we can merge this PR as is, since is fixes a problem and think about the "new line move" in another issue. In this other issue we can discuss better the impact of not having this default new-line added automatically by aiologger.

**Comment by kai3341** [comment]
@daltonmatos got it

**Comment by kai3341** [comment]
@daltonmatos hi again. I've check tests and found this check here:
https://github.com/B2W-BIT/aiologger/blob/master/tests/handlers/test_files.py#L81

**Comment by daltonmatos** [comment]
> Nice catch, @kai3341! Your fix makes total sense.
> I believe that writing a test to validate that `stream.write` is always called with a string ending with `\n` is enough to validate that we won't make the same mistake again.

I think this is the test @kai3341 mentioned here: https://github.com/B2W-BIT/aiologger/pull/79#issuecomment-535216493

**Pull request merged**
